name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Build and Test with Docker
        run: |
          docker build -t sample-c-docker .
          docker run sample-c-docker
